language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      compiler: clang
      addons:
        apt:
          packages:
            - qt5-default
            - qt5-qmake
      deploy:
        edge: true
        provider: pages
        skip_cleanup: true
        github_token: $TRAVIS_DEPLOY_TOKEN
        keep_history: true
        target-branch: gh-pages
        on:
          branch: 
            - master
            
    - os: osx
      osx_image: xcode12.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - qt
      deploy:
        edge: true
        provider: pages
        skip_cleanup: true
        github_token: $TRAVIS_DEPLOY_TOKEN
        keep_history: true
        target-branch: gh-pages
        on:
          branch: 
            - master
      before_script:
        - echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc
        - source ~/.zshrc

    ### TODO: add Windows
      
script:
  - mkdir build
  - cd build
  - qmake ..
  - make