language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      compiler: clang
      addons:
        apt:
          packages:
            - qt5-default
            - qt5-qmake
      # here's my personal CD setup
      after-success:
        - chmod +x ../packages/deb-build.sh
        - ../packages/deb-build.sh
        # - cp TotalReqall ../packages/deb/bin/totalreqall
        # - dpkg-deb --build ../packages/deb totalreqall.deb
        # - mv totalreqall.deb ../docs/binaries
        # - git commit totalreqall.deb -m "Deb file for build $TRAVIS_BUILD_NUMBER"
        # - git push
            
    - os: osx
      osx_image: xcode12.1
      compiler: clang
      addons:
        homebrew:
          packages:
            - qt
      before_script:
        - echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc
        - source ~/.zshrc

    ### TODO: add Windows
      
script:
  - mkdir build
  - cd build
  - qmake ..
  - make
  
# I want to rework the deployment, in my own way.
#deploy:
  #edge: true
  #provider: pages
  #skip_cleanup: true
  #github_token: $TRAVIS_DEPLOY_TOKEN
  #keep_history: true
  #target-branch: gh-pages
  #on:
    #branch: 
      #- master
