name: Build

on: push

jobs:
  linux:
    name: Linux desktop
    runs-on: ubuntu-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          qmake ../TotalReqall.pro
          make
          cd ..

  windows:
    name: Windows desktop
    runs-on: windows-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        
      # get the build environment set up
      - name: Add msbuild to PATH
        uses: seanmiddleditch/gha-setup-vsdevenv@master

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          qmake ../TotalReqall.pro
          nmake

  macos:
    name: macOS desktop
    runs-on: macos-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          qmake ../TotalReqall.pro
          make
          cd ..

  wasm:
    name: WebAssembly
    runs-on: ubuntu-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        with:
          version: '5.13.1' # 5.13.0 was the first with official WASM support
          arch: wasm_32

      # set up emscripten for WASM builds
      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v7
        # needed to make Qt work
        # the sdk-*-64bit are an old naming convention
        with:
          version: sdk-fastcomp-1.38.30-64bit

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          qmake ../TotalReqall.pro
          make
          cd ..

      - name: Prepare deployment
        if: success()
        run: | # the svg line is to get the Qt logo
          mkdir deploy
          cp build/*.html deploy/
          cp build/*.wasm deploy/
          cp build/*.js deploy/
          cp build/*.svg deploy/

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          TARGET_FOLDER: wasm

          # let's use a different profile info
          GIT_DEPLOY_NAME: GitHub Actions runner
          GIT_DEPLOY_EMAIL: github@github.com