name: Build

on: push

jobs:
  linux:
    name: Linux desktop
    runs-on: ubuntu-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Setup packages
        run: |
          sudo apt install build-essential cmake extra-cmake-modules libqt5core5a libkf5i18n-dev libkf5xmlgui-dev libqt5texttospeech5-dev libsword-dev

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .

  windows:
    name: Windows desktop
    runs-on: windows-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
        
      # get the build environment set up
      - name: Add msbuild to PATH
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        
      # ... install KF5 ...
      - name: Install KF5
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
          iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/KDE/craft/master/setup/install_craft.ps1'))
          C:\CraftRoot\craft\craftenv.ps1

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .

  macos:
    name: macOS desktop
    runs-on: macos-latest
    steps:
      # gotta get Qt set up first
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0

      # ... install KF5 ...
      - name: Install KF5
        run: |
          brew untap kde-mac/kde 2> /dev/null
          brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update
          "$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
          "$(brew --repo kde-mac/kde)/tools/install.sh"

        # grab the source
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
